name: Run Telegram Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Запуск кожні 6 годин
  workflow_dispatch:  # Дозволяє запускати вручну

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python3 bot.py
# Оновлення для запуску

