name: Run Telegram Bot

on:
  schedule:
    - cron: "0 */6 * * *"  # Запуск кожні 6 годин
  workflow_dispatch:  # Дозволяє запускати вручну через GitHub Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Remove old session (якщо є)
        run: rm -f bot_session.session

      - name: Run bot
        run: python3 bot.py



